### PR TITLE
feat(invoices): raise an InvoiceEvent before and after invoice save

### PR DESCRIPTION
**Pull request by judereid**
@thejoshsmith We needed the ability to hook in and add some additional data to contacts and invoices when saving. I saw the todos in there so thought I'd have a crack and send through a PR.

Is this what you had in mind? Am I missing anything?

### CODE REVIEW

**Comment by moacode** [comment]
Hey @judereid, looks good to me at first glance. Will have a proper look over it as soon as I can and get it merged.

**Comment by judereid** [comment]
@thejoshsmith polite bump here 😅

Let me know if you don't think you'll get a chance to look at this in the next few days and I'll set us up to use the forked version instead in the meantime.

**Comment by moacode** [comment]
Hey Jude, yeah that's probably the best option as I'm slammed at the moment!

**Comment by moacode** [comment]
@judereid I finally got around to this! Looks great mate, thanks for that. I see you have a branch for naturalpaintco and dinefind—Did you want to get that line item event in here too and I'll merge them all together?

**Review by moacode — APPROVED** [review]

**Comment by judereid** [comment]
@thejoshsmith Nice! Yeah cool, I've pulled in the LineItem one too which is handy for customising the line item descriptions etc. We've been using this in prod across both those projects for a while and haven't had any issues.

FYI as well as #7, you can solve #11 and #8 by setting `$event->invoice->setLineAmountType('Inclusive');` in the InvoiceEvent listener.

**Comment by moacode** [comment]
Awesome, thanks @judereid!

**Comment by moacode** [comment]
> We've been using this in prod across both those projects for a while and haven't had any issues.

Were you planning on purchasing licenses? 😛😛😛

**Comment by judereid** [comment]
> Were you planning on purchasing licenses? 😛😛😛

Will you accept code and a cheese scone as payment? 😅

I'll chase it up today!

**Comment by moacode** [comment]
> > Were you planning on purchasing licenses? 😛😛😛
> 
> Will you accept code and a cheese scone as payment? 😅

Oh mannnn, I haven't had one of those in a long time. Definitely YES!

**Review by moacode — APPROVED** [review]

**Pull request merged**
